/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_sparkle_nestdb_storage_leveldb_Leveldb */

#ifndef _Included_cn_com_sparkle_nestdb_storage_leveldb_Leveldb
#define _Included_cn_com_sparkle_nestdb_storage_leveldb_Leveldb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_Leveldb
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_Leveldb__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_Leveldb
 * Method:    _open
 * Signature: (Ljava/lang/String;)Lcn/com/sparkle/nestdb/storage/leveldb/Leveldb/Status;
 */
JNIEXPORT jobject JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_Leveldb__1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_Leveldb
 * Method:    _get
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_Leveldb__1get
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_Leveldb
 * Method:    _write
 * Signature: (J[B[BJ)J
 */
JNIEXPORT jlong JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_Leveldb__1write
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jlong);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_Leveldb
 * Method:    _scan
 * Signature: (J[B[B)J
 */
JNIEXPORT jlong JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_Leveldb__1scan
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_Leveldb
 * Method:    _snapshot
 * Signature: (J)Lcn/com/sparkle/nestdb/storage/StorageIterator;
 */
JNIEXPORT jobject JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_Leveldb__1snapshot
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
