/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_sparkle_nestdb_storage_leveldb_Leveldb_Status */

#ifndef _Included_cn_com_sparkle_nestdb_storage_leveldb_Leveldb_Status
#define _Included_cn_com_sparkle_nestdb_storage_leveldb_Leveldb_Status
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
