/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator */

#ifndef _Included_cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator
#define _Included_cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator
 * Method:    _hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator__1hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator
 * Method:    _next
 * Signature: (J)Lcn/com/sparkle/nestdb/storage/StorageIterator/Entry;
 */
JNIEXPORT jobject JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator
 * Method:    _remove
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator__1remove
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_com_sparkle_nestdb_storage_leveldb_LevelDbIterator__1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
